version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "ssshotaro44"
      - "kenboo0426"
      - "mhk4022"