version: "3" #composeファイルのバージョン
services: 
  washing-ocr: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/Dockerfile
    tty: true # コンテナの永続化
    volumes:
      - ./cmd:/go/src/app # マウントディレクトリ