# goのバージョン
FROM golang:1.19.3-alpine
# golangci-lintのインストール
RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.35.0

WORKDIR /go/src/app

COPY . .

RUN go mod download

RUN go build -o /docker-gs-ping

EXPOSE 8080

CMD [ "/docker-gs-ping" ]