version: 2.1
jobs:
  build:
    docker:
      - image: golangci/golangci-lint:v1.50
    working_directory: /go/src/washing-ocr
    steps:
      - checkout
      - run:
          name: golangci-lint
          command: golangci-lint run